### ISSUE TITLE
DAO contract Event Refactor and Fetch Proposal

### ISSUE THREAD

**Issue by SampadSikder** [FinCube-23/DAO-Proposal-Governance#19]
This card is responsible for Refactoring the Smart Contract Events so that the backend can listen the socket call properly. We will also add a fetch function which will return all proposal list group by using pagination technique.

https://programtheblockchain.com/posts/2018/04/20/storage-patterns-pagination/

**Comment by FahimDev** [comment]
@SampadSikder  An issue is identified. If we turn on the Docker Containers from the root yml file, I think the audit train is having some env issue. Please check the issue.

**Comment by SampadSikder** [comment]
> [@SampadSikder](https://github.com/SampadSikder) An issue is identified. If we turn on the Docker Containers from the root yml file, I think the audit train is having some env issue. Please check the issue.

The env issue is due to changes in audit trail not being reflected in the global env file. Following the new .env.example standard should solve the issue @FahimDev
